### PR TITLE
Add python 3.5 support

### PR DESCRIPTION
**Pull request by tailaiw**
This is a request per #2

### CODE REVIEW

**Comment by tailaiw** [comment]
@marktibbetts Per your request in #2 regarding Python 3.5 support, we did some investigation and updated the code. In particular, as mentioned in my reply at #2, two issues are resolved.

1. Dictionary is insertion-ordered since Python 3.6. A user may choose `collections.OrderedDict` instead of regular `dict` class in Python 3.5 for an insertion-ordered dictionary. We thought about converting all dict to OrderedDict in the core code but decided not to do so, because we believe the number of py35 users will continue decreasing so we'd keep a convenient API for all py36+ users. Consequently, some results from ADTK may not be guaranteed to have intuitively ordered keys (in dict) or columns (in dataframe) if Python 3.5 is used. We modified our unit tests so it will tolerate the permutation of keys/columns in outputs if Python 3.5 is used. Please note that all other tests, including the test of the values in dict or dataframe, are still enforced, which we believe should satisfy most of the users.

2. The bug of Pandas method `rolling` before pandas v0.25 is confirmed by our testing. The earliest bug-free version we found is pandas v0.25 which requires Python 3.5.3+. This will only impact a user if the transformer `DoubleRollingAggregate` is used with left rolling window defined by offset instead of an integer. If that happened, ADTK now will raise a customized error to suggest the user to upgrade pandas to v0.25+ if Python 3.5.3+ is already being used, or to suggest the user to set an integer parameter if Python 3.5.2 or earlier is being used. We understand this is not a perfect solution, however this is the best we can do given the issue in pandas.

**Comment by tailaiw** [comment]
@marktibbetts It would be greatly appreciated if you may take a look at this and let us know if it meets what you need :)

**Comment by marktibbetts** [comment]
@tailaiw thanks I have bumped this on my priority list to review

**Comment by tailaiw** [comment]
@marktibbetts Appreciate that you captured this. The `packaging` is a new dependency we used here in order to compare the version number of `pandas`. I forgot to include it in the dependency list. I have it installed in my dev environment locally, so I didn't capture it during local testing. However, it is strange why the unit test on Travis is passed too. I will look into it...

**Comment by tailaiw** [comment]
Turns out the reason I missed the bug was `packaging` is also a dependency of `pytest` and `tox`. So it is automatically installed when `pytest` and `tox` are installed, and we cannot capture the bug in the environment of unit test. In other words, this is a bug you cannot capture by unit test :man_facepalming:

**Pull request merged**
